### ISSUE TITLE
Timeout::Error: Waited 1 sec

### ISSUE THREAD

**Issue by masterkain** [ixti/sidekiq-throttled#43]
hello,
when I use this gem I'm getting this in sidekiq.log and workers does not gets executed:
any hint?

```
2018-01-15T09:55:27.514Z 20018 TID-x2oow WARN: {"context":"sidekiq:throttled"}
2018-01-15T09:55:27.514Z 20018 TID-x2oow WARN: Timeout::Error: Waited 1 sec
2018-01-15T09:55:27.514Z 20018 TID-x2oow WARN: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `loop'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `block in pop'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `synchronize'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `pop'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:89:in `checkout'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:61:in `block in with'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-throttled-0.8.1/lib/sidekiq/throttled/queues_pauser.rb:78:in `paused_queues'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-throttled-0.8.1/lib/sidekiq/throttled/queues_pauser.rb:61:in `block (2 levels) in setup!'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-throttled-0.8.1/lib/sidekiq/throttled/communicator/callbacks.rb:61:in `block (3 levels) in run'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-throttled-0.8.1/lib/sidekiq/throttled/communicator/callbacks.rb:59:in `each'
/home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-throttled-0.8.1/lib/sidekiq/throttled/communicator/callbacks.rb:59:in `block (2 levels) in run'
2018-01-15T09:55:32.515Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:55:41.639Z 20018 TID-18dao4 ERROR: Waited 1 sec
2018-01-15T09:55:41.640Z 20018 TID-18dao4 ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
2018-01-15T09:55:43.564Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:55:59.704Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:56:10.737Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:56:21.860Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:56:27.860Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:56:33.861Z 20018 TID-x6ow0 ERROR: heartbeat: Waited 1 sec
2018-01-15T09:56:38.180Z 20018 TID-x6aqk ERROR: Waited 1 sec
2018-01-15T09:56:38.180Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
2018-01-15T09:56:38.180Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `loop'
2018-01-15T09:56:38.180Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `block in pop'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `synchronize'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `pop'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:89:in `checkout'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:61:in `block in with'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq.rb:92:in `redis'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:14:in `enqueue_jobs'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:77:in `enqueue'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/scheduled.rb:68:in `block in start'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:16:in `watchdog'
2018-01-15T09:56:38.181Z 20018 TID-x6aqk ERROR: /home/ubuntu/apps/app-rails/shared/bundle/ruby/2.4.0/gems/sidekiq-5.0.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

**Comment by masterkain** [comment]
bad config on my part

**Comment by rgaufman** [comment]
What was the bad config issue?
